//import { fetchCategories } from '@/http';
import { fetchData } from '@/http';
import Head from 'next/head'
import React, { useEffect } from 'react';


export default function Home() {

  //console.log(props);

  useEffect(() => {
    const res =  fetchData();
    console.log(res);
  }, []); 

  return (
    <>
      <Head>
        <title>Next Js Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      < >
         <h1 className="text-3xl font-bold text-primary-dark">
              Welcome to Next js Blog
          </h1>

      </>
    </>
  )
}

export async function getServerSideProps() {

  //const {data:categories}: AxiosReposse<> =fetchCategories();
  //featch categories
   //const categories=  await fetchData();
//https://blog.logrocket.com/understanding-axios-get-requests/
/*   const headers = {
    // Add your headers here
    'Content-Type': 'application/json',
    Authorization: 'Bearer c0f00e11e1855f49e2f1256d2f1c70d67ed635b3211497c27ab32a8a729c5e006e10bf0c3f773f1258126dcb743df9d1b42470ca9819fe979b86706984f5ab5a04e22df772f44c10e65bbff10569b01ce45df3d487202fe449709e8b3bcd0641cc0a43c1669a4a5a00705361e08c047cfed9a14561031a6ee522d07a2fb56247',
  };

  const options = {
    headers,
  };*/

  // let resp = await fetchData("http://localhost:1337/api/categories",options);
   //const res = await fetch('https://api.github.com/repos/vercel/next.js');
   //const res = await fetch('http://localhost:1337/api/categories');
   
  //const repo = await res.json();
     const res = await fetchData();
    console.log("This data featch in getServerside probs");
   console.log("category",res);
   return {
    props: {categories: "test"}, // will be passed to the page component as props
  };
  
}
